# Please maintain alphabetical order for the top-level settings.
# This makes it easier to find a particular section in this file.

# Note that any changes to this file will need an app restart to
# take effect.
#
#
##########################
#
# ADMIN SITE SETTINGS
#
##########################
# When viewing the details page for a location, there is an 'Edit' link
# at the bottom of the page that takes you to the corresponding location
# in the admin interface. Below, specify the URL for your Admin site.
admin_site: https://ohana-api-demo.herokuapp.com/admin

##########################
#
# FEEDBACK EMAIL SETTINGS
#
##########################
#
# In the feedback_email section, you can add one or more email
# addresses (one per line) that should receive messages submitted
# by users who filled out the Feedback form. You can access the form
# by clicking the 'Feedback' link at the top right of the site.
#
# Make sure to change the email address below to your own,
# otherwise you won't receive any feedback emails.
feedback_email:
  to:
    - ohanapi@codeforamerica.org

##########################
#
# HOMEPAGE LINKS SETTINGS
#
##########################
#
# In the homepage_links section below, you can customize the
# text for the header and links that appear on the bottom half
# of the home page. There are two type of links, "general" and
# "emergency", which correspond to the two "boxes" on the homepage.
#
# To edit the header for each group of links, change the text of
# the keys that are indented below the "general:" or "emergency:" key.
# When we say "key", we refer to any entry in this file that ends with a colon.
# The items under the header key correspond to the text of the links
# under each header.
#
# Clicking a link on the homepage will perform a search for the full
# text of the link, unless the text contains words in parentheses, or
# two words separated by a slash. In those cases, a search will be
# performed for the first word only. For example, clicking on a
# "SNAP (Food Stamps)" or "SNAP/Food Stamps" link will search for "SNAP".
# Keep this in mind when editing or adding link text below.
#
# To add or replace a group of links, indent them below the "general:"
# and/or "emergency:" key. For example, to add a new group of general
# links, you would follow this format:
#
# general:
#   Header Text for New Group:
#     - text for link 1
#     - text for link 2
homepage_links:
  general:
    Health Education Programs:
      - Chronic Disease Self Management
      - Diabetes Prevention
      - Diabetes Education and Support

    Emergent Needs:
      - Free School Supplies

  emergency:
    Food:
      - Food Pantries
      - Meals
      - WIC (Women, Infants & Children)

    Financial Assistance:
      - Bus Fare
      - Gas Money
      - Rent Payment Assistance
      - Rental Deposit Assistance
      - Electric Service Payment Assistance

    Housing / Shelter:
      - Emergency Shelter
      - Low Income/Subsidized Rental Housing
      - Transitional Housing
      - General Minor Home Repair Programs

    Material Goods:
      - General Clothing Provision
      - Diapers
      - Furniture
      - Household Goods

    Health Care:
      - Dental Care
      - General Medical Care

    Legal:
      - General Legal Aid
      - Landlord/Tenant Assistance

    Financial Information & Education:
      - Credit Counseling
      - Debt Management

    Employment:
      - Employment Preparation

    Mental Health and Substance Abuse:
      - Crisis Intervention Hotlines
      - Comprehensive Outpatient Substance Abuse Programs
      - General Counseling Services

####################
#
# INFO BOX SETTINGS
#
####################
#
# In this section, you can define the content for informational boxes that
# will appear at the top of the search results page whenever someone searches
# for a specific keyword or phrase that you define below.
# For example, if someone searches for "food stamps," you might want to display
# information about the federal SNAP program.
#
# To define a new info box, add a new entry indented under "info_box_terms:"
# using this format:
#
# info_box_terms:
#   short_name_for_your_info_box:
#     synonyms:
#       - synonym1
#       - synonym2
#       - synonym3
#     title: title for this info box
#     description:
#       description for this this info box
#     url: website that provides more info
#
# Once you define an info box, all fields are required except for the url.
#
# The name for your info box can be whatever you want. We recommend
# keeping it short and memorable, and making it all lowercase with
# underscores to separate words to keep it more readable.
#
# The synonyms are all the words, phrases, and acronyms that should
# trigger the info box. They must all be lowercase.
#
# The title and description are self-explanatory. On the website,
# the title will appear in bold above the description.
#
# If you provide an url, the "More info..." link in the info box
# will point to it.
#
# To see an info box in action, go to http://ohana-web-search-demo.herokuapp.com
# and search for "wic".
#
# By default, all info boxes use the same HTML template that looks like this:
# <dl>
#   <dt>title_of_info_box</dt>
#   <dd>info_box_description</dd>
#   <p>
#     <a href="info_box_url" target="_blank">More info...</a>
#   </p>
# </dl>
# This HTML is generated by the "render_info_box" method in
# app/helpers/info_box_helper.rb.
#
# If you would like to use a custom template for a particular info box,
# you can create the HTML for it in a partial in the
# "app/views/component/info_box/" directory. The partial must begin with
# an underscore.
# See app/view/component/info_box/_example_custom_template.html.haml for
# and example of a custom template.
#
# Once the template is created, you can assign it to an info box via the
# "custom:" field. An info box that uses a custom template only needs
# the "synonyms:" and "custom:" fields because you would be entering all
# the text directly in the custom template. The value of the "custom:" field
# should be the path to the partial, starting with "component", but without
# the underscore in the partial name. For example, to set up an info box that
# points to "_example_custom_template.html.haml", do this:
#
# info_box_terms:
#   custom_info_box:
#     synonyms:
#       - health care reform
#       - aca
#     custom: component/info_box/example_custom_template
info_box_terms:
  wic:
    synonyms:
      - wic
      - 'women, infants, and children'
      - 'women, infants, & children'
      - wic - women, infants and children
      - wic - women, infants, and children
      - wic - women, infants, & children
      - assistance for mothers
    title: 'Women, Infants, and Children'
    description:
      'Women, Infants, and Children (WIC)
      provides assistance for low-income pregnant, breastfeeding, and
      non-breastfeeding postpartum women, and to eligible infants and
      children up to age 5.'
    url: http://www.fns.usda.gov/wic

  sfmnp:
    synonyms:
      - sfmnp
      - senior farmers' market nutrition program
      - senior farmers market nutrition program
      - food vouchers for seniors
      - food vouchers
    title: Senior Farmers' Market Nutrition Program
    description:
      "Senior Farmers' Market Nutrition Program (SFMNP)
      provides low-income seniors with coupons that can be exchanged for eligible
      foods at farmers' markets, roadside stands, and community-supported
      agriculture programs."
    url: http://www.fns.usda.gov/sfmnp

  snap:
    synonyms:
      - snap
      - food stamps
      - calfresh
    title: SNAP
    description:
      'SNAP offers nutrition assistance to millions of eligible,
      low-income individuals and families and provides economic benefits to communities.'
    url: http://www.fns.usda.gov/snap/supplemental-nutrition-assistance-program-snap

  cdsm:
    synonyms:
      - chronic disease self management
      - cdsm
      - living well
      - hypertension
    title: Chronic Disease Self Management
    description:
      'WIN211 has partnered with the Washington State Department of Health
      to promote the Chronic Disease Self Management Program.
      CDSMP workshops meet once a week for two and one half hours, over six consecutive weeks. Workshops are facilitated by two trained leaders, one or both of whom are non-health professionals with chronic diseases themselves. Workshops are highly interactive.

      Topics include the following
      * How to deal with frustration, fatigue, pain, and isolation.
      * Ways to maintain and improve strength, flexibility, and endurance.
      * Managing medications.
      * How to communicate more effectively with family, friends, and health professionals.
      * Healthy eating.'
    url: https://www.ncoa.org/healthy-aging/chronic-disease/chronic-disease-self-management-program/#sthash.SfcWf0yG.dpuf

  dpp:
    synonyms:
      - diabetes prevention
      - diabetes prevention program
      - dpp
    title: Diabetes Prevention Program
    description:
      "Research studies have found that moderate weight loss and exercise can
      prevent or delay type 2 diabetes among adults at high-risk of diabetes.
      Find out more about the risk factors for type 2 diabetes, what it means
      to have prediabetes, and what you can do to prevent or delay diabetes."
    url: http://www.cdc.gov/diabetes/basics/prevention.html

  des:
    synonyms:
       - diabetes education and support
       - diabetes education & support
       - diabetes education
    title: Diabetes Education & Support
    description:
      "If you are living with diabetes or have a loved with the disease,
      it's important to work together to manage diabetes to stay healthy and
      prevent complications. Managing diabetes is not easy, but support from
      family members can make it much easier. The NDEP has resources for
      making healthy lifestyle choices that not only help people with diabetes
      manage the disease, but also help keep the whole family healthy!"
    url: http://www.ndep.nih.gov

###################################################################
#
# LANGUAGE TRANSLATION LINKS SETTINGS
#
###################################################################

# This represents the most common languages in your community.
# The languages will appear at the top of the home page, and
# clicking on each language will translate the text on the entire
# site into that language using Google Translate.
# The format should be 'Language: code', as shown below.
# To see a list of all supported languages and codes, read the
# "Language reference" section in the Google Translate documentation:
# https://cloud.google.com/translate/v2/using_rest#language-params
# If you do not wish to include any language translation links,
# comment out or delete all of the language settings shown.
language_links:
  - 'English: en'
  - 'Español: es'
  - 'Tagalog: tl'
  - '中文: zh-CN'
  - 'العربية: ar'
  - 'Русский: ru'

######################
#
# SITE LOGO SETTINGS
#
######################
#
# This setting defines the filename for the site logo, which should be placed
# in the 'app/assets/images' directory. The site logo is the one that appears
# in the top left corner of the site.
site_logo: app_logo.png

######################
#
# SITE TITLE SETTINGS
#
######################
#
# This setting defines the HTML title for the site.
# It's the text that the browser displays at the top of the window or tab,
# and the text that the browser uses when saving a bookmark for this site.
#
# When viewing a page other than the homepage, this site title gets appended
# to the end of the page title. For example, if you were viewing the page for
# a location called "Health Insurance TeleCenter", the browser would display
# "Health Insurance TeleCenter | Ohana Web Search" as the page title.
site_title: Ohana Web Search

###########################
#
# PHONE EXTENSION SETTING
#
###########################
#
# Defines the delimiter used for prefixing the phone extension field on the
# location details page. The extension appears after a phone number when
# present in the source dataset.
# Extensions are typically prefixed with 'Ext.', 'extension', or 'x'.
# To just provide a space between the phone number and extension leave this
# value blank or comment out the setting.
phone_extension_delimiter: x

###########################################
#
# SETTINGS FOR TESTS. PLEASE DO NOT MODIFY.
#
###########################################
test:
  admin_site: http://ohana-api-demo.herokuapp.com/admin

  feedback_email:
    to:
      - ohanapi@codeforamerica.org

  homepage_links:
    general:
      Government Assistance:
        - Health Insurance
    emergency:
      Reporting:
        - Domestic Violence

  info_box_terms:
    wic:
      synonyms:
        - wic
        - 'women, infants, and children'
        - 'women, infants, & children'
        - assistance for mothers
      title: 'Women, Infants, and Children'
      description:
        'Women, Infants, and Children (WIC)
        provides assistance for low-income pregnant, breastfeeding, and
        non-breastfeeding postpartum women, and to eligible infants and
        children up to age 5.'
      url: http://www.fns.usda.gov/wic
    snap:
      synonyms:
        - snap
        - calfresh
      title: SNAP
      description: SNAP offers nutrition assistance to millions
    custom_info_box:
      synonyms:
        - health care reform
        - aca
      custom: component/info_box/example_custom_template

  language_links:
    - 'English: en'
    - 'Español: es'
    - 'Tagalog: tl'
    - '中文: zh-CN'
    - 'العربية: ar'
    - 'Русский: ru'

  site_title: Ohana Web Search
